version: '3.5'
services:
    nginx:
        build: ./nginx-rtmp/
        ports:
            - 1935:1935
        volumes:
            - stream-video:/stream
    player:
        build: ./player-docker/
        ports:
          - 8001:80
        volumes:
          - stream-video:/app/player/static/video
volumes:
  stream-video:
